import cv2
import numpy as np

print("Loading image to map...")

start = cv2.imread('src/game_image/start.png')
join_game = cv2.imread('src/game_image/joingame4.png')
join = cv2.imread('src/game_image/join.png')
end = cv2.imread('src/game_image/end.png')
close = cv2.imread('src/game_image/close.png')
checkin = cv2.imread('src/game_image/checkin.png')
no = cv2.imread('src/game_image/no.png')
ok01 = cv2.imread('src/game_image/ok01.png')
ok02 = cv2.imread('src/game_image/ok02.png')
ok03 = cv2.imread('src/game_image/ok03.png')
tectree = cv2.imread('src/game_image/tectree.png')
time = cv2.imread('src/game_image/time.png')
yes = cv2.imread('src/game_image/yes.png')
exit = cv2.imread('src/game_image/exit.png')
returntobase = cv2.imread('src/game_image/rtb.png')
joining = cv2.imread('src/game_image/joining.png')
havejoin = cv2.imread('src/game_image/hvjoin.png')
buy = cv2.imread('src/game_image/buy.png')
back = cv2.imread('src/game_image/back.png')
base = cv2.imread('src/game_image/base.png')
ingameing = cv2.imread('src/game_image/ingaming.png')
backtobase = cv2.imread('src/game_image/backtobase.png')
backtobase2 = cv2.imread('src/game_image/backtobase2.png')
autobuyparts = cv2.imread('src/game_image/autobuyparts.png')
cart = cv2.imread('src/game_image/cart.png')
confirm = cv2.imread('src/game_image/confirm.png')
confirm1 = cv2.imread('src/game_image/confirm1.png')
confirm2 = cv2.imread('src/game_image/confirm2.png')
improvement = cv2.imread('src/game_image/improvement.png')
improvement_ = cv2.imread('src/game_image/improvement_.png')
_purchase = cv2.imread('src/game_image/purchase.png')
purchase_confirm = cv2.imread('src/game_image/purchase_confirm.png')
crew_cancel = cv2.imread('src/game_image/crew_cancel.png')
rtlg_no = cv2.imread('src/game_image/rtlg_no.png')
research = cv2.imread('src/game_image/research.png')
research1 = cv2.imread('src/game_image/research1.png')
box = cv2.imread('src/game_image/box.png')
waiting = cv2.imread('src/game_image/waiting.png')
data = cv2.imread('src/game_image/data.png')
wtlogo = cv2.imread('src/game_image/wtlogo.png')

fire = cv2.imread('src/game_image/6auto.png')

lock = cv2.imread('src/game_image/lock.png')
hsv = cv2.cvtColor(lock, cv2.COLOR_BGR2HSV)
lower_black = np.array([0, 0, 0])
upper_black = np.array([180, 255, 46])
lock = cv2.inRange(hsv, lower_black, upper_black)
crash_warning = cv2.imread('src/crash_warning.png')
crashed = cv2.imread('src/crashed.png')

print("Image loaded successfully")