name: build_prog.yml
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: create venv
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt

      - name: Compile with Nuitka
        run: |
          venv\Scripts\activate
          nuitka --standalone start_prog.py

      - name: copy file to dist
        run: |
          xcopy pp_onnx start_prog.dist\pp_onnx /E /I
          xcopy src start_prog.dist\src /E /I
          copy README.md start_prog.dist\README.md

      - name: zip artifact
        run: |
          Compress-Archive -Path start_prog.dist -DestinationPath AutoNavy.zip

      # 上传到release
      - name: upload to action
        uses: actions/upload-artifact@v4
        with:
          name: AutoNavy.zip
          path: AutoNavy.zip

  upload-release-asset:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v4
        with:
          name: AutoNavy.zip
          path: AutoNavy.zip

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./AutoNavy.zip
          asset_name: AutoNavy.zip
          asset_content_type: application/zip
          token: ${{ secrets.AUTONAVYTOKEN }}
